---
# tasks file for ansible-role-chef-server

- name: Ensure necessary dependencies are present.
  apt:
    name: "{{ item }}"
    update_cache: "yes"
    cache_valid_time: 3600
    state: present
  loop:
    - apt-transport-https
    - tzdata
    - cron

- name: Ensure Chef Server gpg key is present.
  apt_key:
    url: https://packages.chef.io/chef.asc
    state: present

- name: Ensure Chef Server apt repository is present.
  apt_repository:
    repo: "{{ chef_server_apt_repo }}"
    filename: chef-stable
    update_cache: "yes"
    state: present

# we need it to prevent package update via apt-get upgrade
- name: Ensure Chef Server package is pinned.
  copy:
    dest: /etc/apt/preferences.d/{{ chef_server_name }}
    content: |
      Package: {{ chef_server_name }}
      Pin: version {{ chef_server_apt_version }}
      Pin-Priority: 1002

- name: Ensure Chef Server packages is installed.
  apt:
    name: "{{ chef_server_name }}={{ chef_server_apt_version }}"
    update_cache: "yes"
    cache_valid_time: 3600
    state: present
